import {
  AREAS_OF_ACTIVITY_SECTION,
  HERO_BANNER_SECTION,
  HERO_DETAILS_SECTION,
  PARTNERS_SECTION,
  SECTION_WITH_POST,
  SECTION_WITH_POSTS,
  CONTACTS_SECTION,
} from '@components/organisms/RenderComponents/constants';

export const COMPONENTS_WITH_REFERENCES = [
  SECTION_WITH_POST,
  SECTION_WITH_POSTS,
  HERO_DETAILS_SECTION,
  HERO_BANNER_SECTION,
  PARTNERS_SECTION,
  AREAS_OF_ACTIVITY_SECTION,
  CONTACTS_SECTION,
];
